### ISSUE TITLE
Writing a SEQ file in C64 mode skips last character

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#21] opened 2022-08-11 11:41 UTC
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 and xemu (same result on both)
 - ROM Release: (i.e. 920376)
 - Core Commit: f555316

**Describe the bug**
An assembler program that opens a new SEQ file for writing, writes n bytes to it and then closes it, in C64 mode on the MEGA65 core, creates a file of n - 1 bytes, where the last written byte is missing. 

**To Reproduce**
1. Mount the included disk image.
2.  go 64
3. load "*",8,1
4. sys 49152
5. Look at the code at $c000, or read the enclosed source code
6. Examine the new seq file "test"
7. The program clearly writes "abc" to the file, but the file only contains "ab".

[rombug.zip](https://github.com/MEGA65/mega65-rom-public/files/9308238/rombug.zip)

**Expected behavior**
The file should contain "abc"

**Screenshots**
![image](https://user-images.githubusercontent.com/1001548/184125247-4fce7e1d-fd91-4427-ad8c-5afc4be37218.png)

![image](https://user-images.githubusercontent.com/1001548/184125444-c74180b4-2aa6-47b1-9d3f-69bf95c34a44.png)

**Additional context**
Running the same program in VICE C64 (x64) results in all the values being written to the file.

**Comment by johnwayner** [comment] 2023-12-14 20:58
I've spent a fair amount of time over the last couple of days I've had available looking into this bug.  While I don't have a fix for it yet, I know why it's happening.  And it's actually worse than it appears from this test.

First of all, this is a bug in the DOS ROM.  It therefore effects interactions with mounted d81s and physical disks in the internal drive.  IEC devices are not effected as best I can tell.

The issue is caused by DOS' `hciout` routine (called by eventually when a `bsout` ($FFD2) kernal call is made).  `hciout` is buffering the input into a var called `data` at the very end of the routine.  Earlier, it checks if there was a previous call that buffered something in there. If so, it will move it into the channel's buffer.

The net result of this is that `hciout` calls always one character behind.  This can be demonstrated by modifying the attached program to open two files at once and to write to them alternatively.  Each character will end up in the wrong file because it is not actually written to the channel buffer until the next call (with the wrong channel information).

So how in the world has this not been noticed before?, you ask :) Well, this buffered byte is actually written to the buffer on an `hunlisten` call as well.  BASIC calls unlisten or clrchn a decent amount and thus causes that character to get written.

The test program attached here can be modified to call `unlisten` ($FFAE) or `clrchn` ($FFCC) before closing and the final byte will be written.

Unfortunately, I don't fully grok the nuances of the DOS code.  My naive attempts to immediately move the byte into the channel's buffer have caused other terrible side effects.  Perhaps this bit of information will help someone else or start a conversation that leads to a solution.

I haven't totally given up, but I likely won't be able to work on it for a couple days and wanted to get my findings out there.

**Closed** 2023-12-21 21:18 UTC
Labels: bug
