### ISSUE TITLE
NO SCROLL locks up in list while at 1MHz

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-rom-public#25] opened 2022-10-04 07:18 UTC
This was created first as a core bug, but it might be possible that this is a ROM bug instead. I can't see any special NO SCROLL handling while the core is in "default mode".
1. SPEED 1
2. LIST
3. press NO SCROLL while listing
4. press RUN/STOP

after this you can't get out of it except by an RUN/STOP-RESTORE. Does not happen with more speed.

Original Issue: https://github.com/MEGA65/mega65-core/issues/577

**Comment by dropnine** [comment] 2022-11-05 17:05
I updated to the release 2 core and 377 rom.  The issue still exists however, when listing **_anything_** in 1MHz mode run/stop puts the m65 into an unresponsive state until the CAPS LOCK is pressed or a soft reseat with the run/stop-restore.  When pressing the no-scroll key, pressing the run/stop key results in the same process.

This does not effect the internal ML Monitor.

**Comment by dansanderson** [comment] 2022-11-07 08:18
I can reproduce this without pressing NO SCROLL first. SPEED 1; LIST; RUN/STOP will hang.

This appears to hang near $995E similar to this other unusual hang in 1 MHz mode: https://github.com/MEGA65/mega65-core/issues/630

Core 20221008.23,2f545d1 (should be similar to v0.95), ROM 920377.

**Comment by dansanderson** [comment] 2023-03-06 09:05
We might want to group all of the 1MHz crashes, as they might be related. For example, it seems like every BASIC 65 error hangs in 1MHz mode. https://github.com/MEGA65/mega65-core/issues/630

**Comment by lgblgblgb** [comment] 2023-03-06 09:43
@dansanderson Then I would suggest to create label "1MHZ-CRASH" or something, and apply every issues may have connected. Then it's easy to pull every issues having this label applied.

**Comment by dansanderson** [comment] 2023-08-03 18:17
I can reproduce this at 0.95 core master,20221012.18,93d55f0 and ROM 920377, but not at ROM 920384 with the same core. I believe this was fixed by accident due to nearby changes.

**Closed by dansanderson** 2023-08-03 18:17 UTC
Labels: bug
