### ISSUE TITLE
MOUSE does not work with port 2

### ISSUE THREAD

**Issue by Schwefelholz** [MEGA65/mega65-rom-public#52] opened 2023-04-04 09:12 UTC
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65, NexysA7
 - ROM Release: 920377
 - Core Commit: 93d55f0

**Describe the bug**
According to the BASIC reference, the second parameter of the MOUSE command specifies the port the mouse is connected to:
`MOUSE ON,[1,2,3]`
However, no matter what I put there, MOUSE is always just working on port 1. The second parameter seems to be ignored. 

**To Reproduce**
1. Connect mouse to port 2
2. Issue `MOUSE ON,1`, `MOUSE ON,2` or `MOUSE ON,3`
3. The mouse connected to port 2 does not react.
4. Connect mouse to port 1
5. repeat step 2
6. Mouse is always moving sprite 0

**Expected behavior**
`MOUSE ON,2` and `MOUSE ON,3` should react on a mouse connected to port 2.

**Screenshots**
none

**Additional context**
none

**Comment by dansanderson** [comment] 2023-04-04 17:39
There's a similar issue with paddle support: https://github.com/MEGA65/mega65-rom-public/issues/35

Notes on code review:

* Command sets bits 7 and 6 of `mouse_enable` for use by `mouse_irq` in `system.src` to select port 1, 2, or both.
* This is stored directly in `d1pra = $dc00`, port A on CIA 1. I'm looking for more docs on this, but I see confirmation in the Raeto West book, figure 5-8 on page 125. This appears to be the correct way to select the paddle port.
* POTX and POTY are read directly to check the position change.

Next step is to confirm this behavior in a debugger and/or with a similarly written test routine. If this piece is working as intended, then the gap may be in the core implementation. This would be consistent with the missing paddle support issue.

**Comment by ki-bo** [comment] 2023-09-03 18:22
The buttons are read correctly from port 2 if using `MOUSE ON,2`, but the coordinates are still read from port 1.

**Comment by dansanderson** [comment] 2023-09-24 18:38
This is fixed in the latest development core and will be in v0.96. 🎉

**Closed by dansanderson** 2023-09-24 18:38 UTC
Labels: bug
