### ISSUE TITLE
Bugs in Mouse Command

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-rom-public#8] opened 2022-05-29 14:54 UTC
@ruesch repoted this as https://github.com/MEGA65/mega65-core/issues/563

![IMG_20220528_193727](https://user-images.githubusercontent.com/12908574/170867790-22dfae76-9e02-40ba-bc61-eea95a91e95c.jpg)

> The following bugs have been noticed (80Column Mode). I used the original 1351 Mouse and a USB Mouse with Micromys V5.

> The results are the same:

> - If i use the "MOUSE ON,1" Command in Basic Programs, its impossible to abort with RUNSTOP, only RUNSTOP/RESTORE works.

> - The Sprite jumps over some pixels in all directions. its difficult to reach a special position.

> - The x and y coordinates in RMOUSE seems not correct. If i move exact 64 pixels in x-coordinate RMOUSE shows only a difference about 31 pixels.

> the x,y parameter in MOUSE ON doesn't work.

> in direct mode i can reactivate the machine only with RUNSTOP/RESTORE.

See also: https://www.forum64.de/index.php?thread/126476-bugs-in-mouse-command/

**Comment by Edilbert** [comment] 2022-05-30 16:02
I attached a 1531 mouse to port 1 and did some tests with MOUSE ON,1 and then reading the position with 
MOUSE X,Y.
I can confirm, that the mouse jumps and the X and Y coordinates too.
Then I tracked the readout of the sprite 0 (default mouse sprite) register ($D000 and $D001) and found the same jumps there. These are set from the kernal mouse driver, which reads the POTX and POTY register at $D419/$D41A.
These seem to cause the issue. They are jumping often, even while moving the mouse smoothly.

So I think it's a VHDL issue: The POTX/Y registers are not set according to the mouse movement.
The mouse driver work smooth in the emulator XEMU, another hint, that this is not a ROM issue.

**Comment by dansanderson** [comment] 2023-02-27 08:47
As of ROM 920383 and core 20221012.18,93d55f0, I'm not noticing any issues with a Commodore 1351 mouse or an Amiga mouse, with MEGA65 Configuration set appropriately. I vaguely recall reproducing jitter with 1351 mice months ago, but I don't know if a specific change addressed this issue.

I can exit a BASIC program with the mouse active using RUN/STOP. RMOUSE reports the mouse position precisely: X coordinates in range 24-343 and Y coordinates in range 50-249, in 80x25 mode. (That's an unusual range, but it works, and I'm reluctant to change it because it would break existing software.)

I'm closing this as fixed. Please re-open if this is still an issue.

**Closed by dansanderson** 2023-02-27 08:47 UTC
Labels: bug
