### ISSUE TITLE
80x50 mode boot command displays garbage text

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#43] opened 2023-02-26 23:31 UTC
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920382
 - Core Commit: 1586ad4

**Describe the bug**
When in 80x50 text mode in the beta ROM, and running `boot` without an AUTOBOOT.C65 file, the bottom half of the screen fills with garbage text.

**To Reproduce**
1. Mount a disk without an AUTOBOOT.C65 file.
2. Hit `escape+5` to enter 80x50 text mode.
3. Type `boot` and hit return

**Expected behavior**
Something like `62,FILE NOT FOUND,00,00` should be displayed.

**Comment by dansanderson** [comment] 2023-02-27 07:14
Nice find!

**Comment by dansanderson** [comment] 2023-02-27 07:34
I can get 80x50 mode to misbehave on various disk errors. It's not just a temporary cosmetic issue, either: I can get the machine stuck by simply trying to clear the screen in this condition. I wonder if 80x50 mode is accidentally overlapping DOS buffer space.

**Comment by snoopy-f64** [comment] 2023-02-27 08:45
I can not reproducwe the BOOT error with the latest Xmega65 emulator.
![xmega65_920382_b](https://user-images.githubusercontent.com/66867430/221515790-10d0f657-244e-467d-9519-d32446936f3e.png)
![xmega65_920382_a](https://user-images.githubusercontent.com/66867430/221515792-70bc1eda-4fe4-427c-9923-3a86a436ff7c.png)

Maybe it's a issue regarding only on real MEGA65?

**Comment by woepaul** [comment] 2023-03-03 20:54
There a plenty of ways to produce garbage text in 80x50 mode.
It's as simple as: `speed 1`

https://user-images.githubusercontent.com/2370928/222827517-609f3b98-1da1-43d0-9670-02bf8f456923.mp4

**Comment by woepaul** [comment] 2023-03-03 20:56
Same for reading the directory on external drives. E.g. `dir u10` (reading from an external 1571):
![image](https://user-images.githubusercontent.com/2370928/222827885-ee4c6ea4-82b7-4c1c-bd3a-f9ef9c38c94a.png)

**Comment by woepaul** [comment] 2023-03-03 21:01
Notice the similarity between the `dir u10` case and `speed 1`. Looks as if  `dir u10` somehow implies `speed 1` (or whatever is responsible for corrupting the screen).

**Comment by dansanderson** [comment] 2023-06-01 17:14
Something as simple as PRINT CHR$(7) (which should ring the bell) can also cause a lower half of screen of garbage text.

![CleanShot 2023-06-01 at 10 13 51](https://github.com/MEGA65/mega65-rom-public/assets/408973/93f1b7b1-b33f-42b2-8c96-df413e9627a6)

Oddly, the "PRINT CHR$(7)" also disappears, as shown in the screenshot.

**Comment by dansanderson** [comment] 2023-08-01 02:54
I have confirmed that these symptoms all have the same cause: features of the kernel that set Slow mode via a write to $D031, tripping Hot Registers that reset SCRNPTR (D060-D063). Bell and DOS both set D031 for Slow mode, and `SPEED 1` obviously does as well.

80x50 relocates screen memory to 4.0800, and these various actions are changing the VIC screen memory pointers (SCRNPTR, 28 bits, specifically D062 is the bank) back to 0.0800 without changing other parameters. This explains why the flip back causes some text to disappear: that was text written on the 4.0800 screen memory and not the 0.0800 screen memory. `POKE $D062,4` restores the 80x50 screen pointer. It's possible that this is updated via VIC-II hot registers $D018/$DD00.

`bell:` tries to clear the FAST bit in D031 with:

```
lda #%01000000
trb vic+49             ; D031
```

`disk_cli:` does something similar, which is used by most disk and serial operations.

The ideal fix would be in the core, with special handling for D031 to compare bit values before and after a change and only update Hot Registers based on bits that have changed. I don't know if this is plausible or if this might have backwards incompatibility issues. A workaround would be for the ROM to test for 80x50 mode and restore SCRNPTR after each flip of the FAST flag, which might cause a brief flicker.

**Comment by lgblgblgb** [comment] 2023-08-01 06:34
@dansanderson I see a general problem here, just like the $D018 issue in Xemu. There, there was a logic to detect if some value is written and ignoring triggering hot-reg propagation event in that case, which was wrong. I am afraid if this thing is fixed in MEGA65-core, similar issue would be then. Ie, even if the same value is really written, maybe it must be propagated still, as it would mean some change on native VIC-IV regs if those were written before. I think, the solution is more to disable hotreg events so no triggering is done, if you really need to avoid this, but otherwise it's the desired behaviour and only way to be consistent not to "lose" change in some cases.

**Comment by snoopy-f64** [comment] 2023-08-01 10:25
I would completely abandon the 80x50 text mode. In my opinion, you can't work seriously in this mode for a long time anyway, and I don't think it's easy to get a grip on moving the text memory without causing incompatibilities elsewhere. The "big" problems started when the 80x50 text mode was introduced. There are more tightly meshed functions in the ROM than one might think at the beginning. In my opinion, the 80x50 text mode has no place in the ROM, it "doesn't fit" ;-)

**Comment by dansanderson** [comment] 2023-08-02 20:22
The good news is, I can demonstrate disabling Hot Registers fixing this issue from BASIC:

1. ESC 5 to enter 80x50 mode
2. `poke $d05d,peek($d05d) and $7f` to clear HOTREG
3. Ctrl-G : bell rings, SCRNPTR is not updated

The bad news is, re-enabling HOTREG causes all Hot Register changes to propagate, so I can't disable Hot Registers *just* during the change to D031. This behavior makes HOTREG especially not useful—at least for the ROM, which depends on HOTREG being enabled in many places. I think HOTREG was designed for programs that just turn it off and leave it off.

So I either need HOTREG behavior to change in the core, or I need to rewrite the ROM so that M65 mode runs with HOTREG disabled. 😵‍💫 I'll start another core issue so we can discuss the possibility of changing HOTREG.

**Comment by lgblgblgb** [comment] 2023-08-02 21:03
@dansanderson That's really interesting. I would even consider this a mega65-core bug maybe? I mean, for me at least, the point of hotreg enable/disable, that I can disable propagation of hotreg "triggers" then I can enable hotregs again, without the effect of "playing back" those triggers, otherwise the possibility to enable/disable hotregs actually does not make too much sense (unless someone wants to disable hotregs _forever_). I am not sure how it should work, but for me it sounds like a core bug, but for sure, I can be totally wrong ...

**Comment by snoopy-f64** [comment] 2023-08-02 21:15
> So I either need HOTREG behavior to change in the core, or I need to rewrite the ROM so that M65 mode runs with HOTREG disabled. 😵‍💫 I'll update the related core issue so we can discuss the possibility of changing HOTREG.

That's what I meant by:

> In my opinion, the 80x50 text mode has no place in the ROM, it "doesn't fit" ;-)

I know the ROM a bit and I definitely wouldn't make such changes here just to get the 80x50 text mode to work. Here I see a greater risk for unwanted side effects, which for me are out of proportion to the benefit.

Maybe there is something feasible in core that can be implemented without unwanted page effects? That's what I meant by "doesn't fit in the ROM". I know the ROM a bit and I definitely wouldn't make such changes here just to get the 80x50 text mode to work. Here I see a greater risk for unwanted side effects, which for me are out of proportion to the benefit.

Maybe there is something feasible in core that can be implemented without unwanted page effects? But I would definitely not change the ROM much for this purpose only.

**Closed** 2023-08-02 22:33 UTC
Labels: bug

**Comment by dansanderson** [comment] 2023-08-02 23:34
I have submitted a ROM change that stashes and restores SCRNPTR for speed changes. This appears to resolve all of the known issues. I consider it a kludge because it doesn't account for all hot registers, and requires that all manipulation of the FAST bit to go through centralized routines. I'm willing to extend the kludge for a few more registers if needed, but I agree that we should be considering an alternate design for hot registers instead. That discussion continues here: https://github.com/MEGA65/mega65-core/issues/714

I understand and partly agree with your point about the ROM not being a good fit with newer MEGA65 hardware features. The ROM is unique in that it's the largest piece of legacy C65 software that we all run regularly on a MEGA65, but we also want to run it at 40 MHz by default and take advantage of newer MEGA65 features. The current design of Hot Registers makes sense for newly written software for the MEGA65, which can just disable HOTREG as part of requesting a "full VIC-IV mode." I think it'd be a shame to say that it's impractical for the ROM to use any VIC-IV features, but I would agree that we need more consideration in the core for a mixed-use mode before we go any deeper.

We're probably converging on feature complete for the closed ROM, so it's probably a non-issue. I'm not opposed to new features, but they're getting increasingly expensive to add, and we have limited resources. I'd rather invest in polishing the features we have, and formalizing and documenting extension APIs that third-party programming apps can use. A third-party language interpreter that launches from disk or cartridge can define its own boot state and command set that uses all of the VIC-IV.

**Comment by dansanderson** [comment] 2023-08-04 22:50
An update for the record (issue is still closed): This fix has been replaced by a new fix that depends on a core change. It does not cause regressions with older cores, but also does not fix the issue for older cores. The latest development core adds a feature to Hot Registers to allow updating VIC-II/III registers without propagating to VIC-IV registers while still leaving Hot Registers enabled at the end of the procedure. This is pretty much only useful for the ROM to update FAST while leaving video-related registers in an inconsistent state and HOTREG enabled, which is what the ROM now does.

All arguments against abusing Hot Registers and 80x50 mode are still valid. But this is what we're going with. ;)
