### ISSUE TITLE
IEC Disk Drive doesnt read contents of a directory

### ISSUE THREAD

**Issue by oe3gwu** [MEGA65/mega65-rom-public#84] opened 2023-09-30 11:57 UTC
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920386
 - Core Commit: 3253c5d

**Describe the bug**
As discussed with Stephen - here the Bug report.

This Bug only happens in MEGA65 mode. GO64 Mode or on my C128DCR, this doesnt happen.

When listening the directory of a 1581 Disk on the internal drive all works perfect. When trying to listen the disk using my Read Admiral Fire Drive 2k or my real 1581, I dont get the Disk contents. But loading a file using a filename works perfect.

I do not have something else connected then the disk drive on the IEC bus.

**To Reproduce**
1. Go to MEGA65
2. Load"$",8 or Dir
3. Wait until finished

**Expected behavior**
Expected would be that I could listen the entire directory of a drive. 

**Screenshots**
Internal Disk Drive:
![IMG_3818](https://github.com/MEGA65/mega65-rom-public/assets/17622063/b6d2b3ce-c74b-4f72-bd43-748a812fbe51)

External 1581:
![IMG_3813](https://github.com/MEGA65/mega65-rom-public/assets/17622063/f7f7bae6-8ce0-4c93-90b1-e7459c1e8c13)

External FireDrive 2k:
![IMG_3814](https://github.com/MEGA65/mega65-rom-public/assets/17622063/74b1d2c5-2274-4da8-8b05-325b3219b287)

GO64 Mode:
![IMG_3817](https://github.com/MEGA65/mega65-rom-public/assets/17622063/509d977e-bff2-4839-bc0f-7154f5b4869d)

![IMG_3809](https://github.com/MEGA65/mega65-rom-public/assets/17622063/f1cf67dc-ee32-436a-8a60-2e4a7c76b41f)

**Additional context**
I am available on Discord as "Jerrec" for further testing.

**Comment by gardners** [comment] 2023-09-30 21:13
Thanks for logging this.  I _suspect_ it might be that in MEGA65 mode, the ROM is offering fast serial mode, but then it doesn't actually work.  But I'm not 100% confident that this is the cause.  There is an effort underway to implement hardware-accelerated IEC communications to improve a lot of this.

Meanwhile, can you test it with SLOW and with FAST mode, to see if there is any difference?

**Comment by oe3gwu** [comment] 2023-09-30 21:18
Yeah sure can test this tomorrow. If I have questions, I get in touch via discors.

**Comment by oe3gwu** [comment] 2023-10-01 18:24
Changing between FAST and SLOW (1MHz) doesnt change anything for me, but I found out, that a LOAD"$",8 doesnt work but "DIR" does work actually.

I havent tried, but I think with 920287 both commands worked, because I actually NEVER used "DIR".

**Comment by Schwefelholz** [comment] 2023-10-03 16:00
I expect your 1581 is set to device unit # 8 and you changed the internal drive's unit # to 10 in the freezer?
Have you tried to change your 1581 to unit # 10 or 11 and tested again?
I recall there is an issue with the 1581 that it does not work correctly anymore once the freezer was entered. At least this is the case for me.
My 1581 is set to unit # 11 and it is working fine (loading, saving, displaying directory) until the freezer is entered once.

**Comment by oe3gwu** [comment] 2023-10-03 16:43
1. I changed of course the disk drives in the freezer from 8 to 10 and 9 to 11.
2. No, I havent, I can try.
3. I never experienced that issue before.

Also I tried today, an older Kernel doesnt have this issue. I attach pic's asap. It is definately a new thing.

**Comment by Schwefelholz** [comment] 2023-10-04 06:45
Maybe a duplicate of https://github.com/MEGA65/mega65-rom-public/issues/80#issue-1909521382?

**Comment by oe3gwu** [comment] 2023-10-04 14:58
Short Update. Also happens when external IEC Drive is configured as Drive 10 with the Kernal 920386. It works with 920377.

![IMG_3873](https://github.com/MEGA65/mega65-rom-public/assets/17622063/43509104-38a8-4e34-a4b3-5f3f09570493)

**Comment by oe3gwu** [comment] 2023-10-04 15:02
> Maybe a duplicate of [#80 (comment)](https://github.com/MEGA65/mega65-rom-public/issues/80#issue-1909521382)?

My behaviour is exactly the opposite. DIR works but LOAD doesnt.

**Comment by Schwefelholz** [comment] 2023-10-04 16:31
I got it now an can reproduce it on a 1581, 1571 and FNX1591.
ROM 920385

**Comment by dansanderson** [comment] 2023-10-05 02:40
If someone who can repro this has a chance, it'd help to narrow down which ROM introduced the offending change. Above we have a range of 920287 to 920385. The offending change is probably one of the "CBDOS clean-up" changes in the middle of that range. Thanks!

**Comment by Schwefelholz** [comment] 2023-10-05 05:42
I might be too dumb: Where do I get older ROMs? On file host, I can see a couple of experimental ones, 920377 and 920388, but nothing else.

**Comment by dansanderson** [comment] 2023-10-05 06:19
Yeah it's not obvious. :) Versions before 920377 will be on the ROM "Stable" page. Click the grey "All versions" box to get a list: https://files.mega65.org?id=54e69439-f25e-4124-8c78-22ea7ddc0f1c

That's when we changed how we label releases to make it more obvious that 920377 was considered part of the v0.95 release package. Going forward, the intermediate releases will be on the ROM "Beta" page, and the "Stable" page will just be for what's in the stable release packages. (We will promote a release from "beta" to "stable" as part of the upcoming v0.96 release package.)

**Comment by Schwefelholz** [comment] 2023-10-05 14:45
Seems as if the last ROM the directory of external IEC drives was displayed after `LOAD"$",11` was 920384.
From 320385 the load process shows and `LIST` just shows the directory's first line (Disk Name) and `READY.`

`LOAD"$",11`
` `
`LOADING $`
`UNIT:11`
` `
`READY.`

In 920384 the `UNIT:11` after `LOADING $` is not displayed and `LIST` displays the full directory.

`LOAD"$",11`
` `
`LOADING $`
`READY.`

**Closed** 2023-12-09 23:34 UTC
Labels: bug, IEC
