### ISSUE TITLE
COLOR with argument greater than 15 let the cursor disappear

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#75] opened 2023-09-07 11:59 UTC
- ROM Release: > 920377

Using the COLOR command with argument > 15 let the cursor disappear.

Works correct with 920377.

**To Reproduce**

e.g. COLOR 17

Found by user MC64 of Forum64:

https://www.forum64.de/index.php?thread/139469-color-mit-werten-gr%C3%B6%C3%9Fer-15-und-der-cursor-geht-hopps/

**Comment by dansanderson** [comment] 2023-09-08 23:23
This is a core issue fixed by this pull request: https://github.com/MEGA65/mega65-core/pull/716

It will be included in the v0.96 core release.

**Comment by dansanderson** [comment] 2023-09-10 02:40
Sorry, I jumped to a conclusion here. The issue fixed by the core change is the cursor "disappearing" for colors 8-15, which is caused by a broken implementation of character properties.

This issue is reporting a behavior where the cursor specifically (not characters in general) doesn't render the upper palette reverse attribute correctly during cursor blink. This is a ROM bug from the screen editor rewrite. I'll reopen and look into it.

Thanks! Sorry for the confusion.

**Comment by dansanderson** [comment] 2023-09-10 05:48
My previous explanation is still accurate: the core change is meant to fix this issue. Character attribute combination misbehavior is one of several fixes to VIC-III bugs. Xemu needs to be updated with the character attribute fix. (I still need to put this change behind the VIC-III compatibility flag, so C65 prototype ROMs get the legacy behavior. I'll make sure this happens before the next release.)

This is only visible in newer ROMs because a recent revision changed the way the cursor is rendered. The old behavior used reverse character screen codes for the cursor blink. The new behavior uses the reverse character attribute. The legacy attribute behavior is incapable of rendering both the reverse attribute and the "bold" upper palette attribute at the same time, so the cursor's reverse state appears the same as its normal state (i.e. the cursor is not visible).

**Comment by dansanderson** [comment] 2023-09-12 00:29
I've decided to go back to the reverse-character style of cursor rendering, which will fix this without the core change I mentioned. The core change will be updated so that it is only enabled by programs that want it, to preserve backwards compatibility with the original attribute behavior. (The new attribute behavior is better, but the C65 prototype used the old behavior, so we want to keep it around.) So it's better for the ROM to render the cursor in a way that's compatible with the original attribute behavior. 

Apologies for the confusion. :) The fix will be in the next beta ROM.

**Closed** 2023-09-12 03:23 UTC
Labels: new
