### ISSUE TITLE
MONITOR should initialize at least the flags register when entered

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-rom-public#67] opened 2023-08-16 13:26 UTC
If some uses the `MONITOR` command to enter the monitor the register view shows SR being zero (and the corresponding per-bit display as well at the right). After assembling a single `RTS` instruction and using the `J` command to call, SR is changed, though nobody set any flag bits.

I guess the biggest problem here, that the `E` bit shows the 8/16 bit stack mode, which seemingly changed, being `0` before, and `1` after. Though for sure the situation: MONITOR just does not initialize its SR "storage" according to the CPU flags register. As @dansanderson said, it's done when MONITOR is entered via a `BRK` opcode. So my only point here, that it should be also done when entered from BASIC65 via the `MONITOR` command.

I tested this with ROM V920377, just because that was installed with Xemu on this machine where I am right now :)

Discord discussion link: https://discord.com/channels/719326990221574164/782757495180361778/1141273272000974869

**Comment by dansanderson** [comment] 2023-08-27 03:13
Specifically, someone noticed a case where entering the monitor with the `MONITOR` command resulted in an initial display where `SR=00` and `NVEBDIZC=11111111`. These should represent the same value, but for someone in some case it wasn't. I've been unable to reproduce this.

![image](https://github.com/MEGA65/mega65-rom-public/assets/408973/9f77ad2d-746d-4f6e-89d0-796799d10593)

`Mon_Call` is responsible for setting the initial values when entering via `MONITOR`, and it looks like the code is attempting to zero out the register view in $07-$0C. This might be a bug on its own, as I think it should be zeroing out $05-$0A (to include AC ($06) and SR ($05)). That doesn't explain the screenshot on its own.

`Mon_Register` is responsible for printing the register values, and it appears to be using SR to generate the flag string. Just on code review I can't see how these values would differ.

Of course this is all cosmetic, but it's worth paying attention to the details to avoid confusing people.

**Comment by johnwayner** [comment] 2023-11-30 20:12
The initial zeroing of SR when entering from basic matches the C128 monitor behavior. Moreover, if the RTS test that LGB suggests results in the same result on C128: SR=30.

A difference I do note is that on the C128 the initial PC value is FB000 (where the monitor lives in its ROM) while on Mega65 the monitor's initial PC value is 00FFA2 (the monitor exit vector, strangely).  This hardly matters though.

I have no idea how the SR=00 but all flags as 1 happened. But will note that it happened on Xemu.  Not to blame Xemu, just as a data point.

**Comment by dansanderson** [comment] 2023-12-31 20:04
Given that the E/B flag thing happens on the C128, I'm inclined to say it's working as intended. It'd be fun to dig up an explanation but it doesn't seem specific to BSMON.

We haven't been able to repro the mis-reported status register thing. The code for printing the status register as a string of `-` and `1` is pretty simple, and i don't see how SR=00 would produce `11111111`. (I did a couple of tests to see if flag status on entry affects the algorithm but I couldn't find anything.)

Resolving for now. Please re-open if repro steps are found.

**Closed by dansanderson** 2023-12-31 20:04 UTC
Labels: bug
